# Docker file authentication
FROM python:3
ADD requirements.txt .
RUN pip install -r requirements.txt
RUN mkdir /logs
ADD test.py .
ADD authentication_test.py .
CMD [ "python3", "authentication_test.py" ]