# Docker file authentication
FROM python:3
ADD requirements.txt .
RUN pip install -r requirements.txt
RUN mkdir -p /app/logs
ADD test.py .
ADD authentication_test.py .
CMD [ "python3", "test.py", "authentication_test.py"]