# Docker file content
FROM python:3
ADD requirements.txt .
RUN pip install -r requirements.txt
RUN mkdir -p /app/logs
ADD test.py .
ADD content_test.py .
CMD [ "python3", "test.py", "content_test.py" ]