# Docker file authentication
FROM python:3
ADD requirements.txt .
RUN pip install -r requirements.txt
RUN mkdir -p /authentication_test/logs
ADD test.py .
ADD authentication_test.py .
ENV LOG=1
CMD python3 authentication_test.py