version: '3'
services:
  fastapi_server:
    image: datascientest/fastapi:1.0.0
    ports:
      - "8000:8000"
    restart: always
    networks:
      - mynetwork

  authentication_test:
    build:
      context: .
      dockerfile: Dockerfile_authentication
    volumes:
    - type: volume
      source: log_volume
      target: /app/logs
    environment:
      - LOG=1
    networks:
      - mynetwork
    depends_on:
      - fastapi_server

  authorization_test:
    build:
      context: .
      dockerfile: Dockerfile_authorization
    volumes:
    - type: volume
      source: log_volume
      target: /app/logs
    environment:
      - LOG=1
    networks:
      - mynetwork
    depends_on:
      - fastapi_server

  content_test:
    build:
      context: .
      dockerfile: Dockerfile_content
    volumes:
    - type: volume
      source: log_volume
      target: /app/logs
    environment:
      - LOG=1
    networks:
      - mynetwork
    depends_on:
      - fastapi_server

volumes:
  log_volume:

networks:
  mynetwork: