# Docker file authorization
FROM python:3
ADD requirements.txt .
RUN pip install -r requirements.txt
RUN mkdir -p /app/logs
ADD test.py .
ADD authorization_test.py .
CMD [ "python3", "test.py", "authorization_test.py" ]